# Generated by `bun run formula` in TheFox666/mduct — edit there, not here.
class Mduct < Formula
  desc "Every MCP server as a Unix tool: pipe it, script it, run it by hand"
  homepage "https://github.com/TheFox666/mduct"
  version "0.6.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/TheFox666/mduct/releases/download/v0.6.0/mduct-darwin-arm64"
      sha256 "4b2dd9a5148ae9b5f1a102e4ede182fccd48ea493a56b19990f3f746060f2269"
    end
    on_intel do
      url "https://github.com/TheFox666/mduct/releases/download/v0.6.0/mduct-darwin-x64"
      sha256 "ca5501990d8cb686df2288e91c2b8ec5a80ad2d62f50465bfba7250a20e22b24"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/TheFox666/mduct/releases/download/v0.6.0/mduct-linux-arm64"
      sha256 "edf5f097bfdf917a4c3030c1a0199bb731936c8c7fe4393fe15e4c867b6edaad"
    end
    on_intel do
      url "https://github.com/TheFox666/mduct/releases/download/v0.6.0/mduct-linux-x64"
      sha256 "7967d8ae694a9d885d4654d47d55bb220885e54e0d183334eccacdad4a9074f5"
    end
  end

  def install
    bin.install Dir["mduct-*"].first => "mduct"
  end

  def caveats
    <<~EOS
      Point mduct at your MCP servers in ~/.config/mduct/servers.jsonc, or import
      the ones you already have:

        mduct import            # lists servers found in your Claude configs
        mduct import gitlab     # copies one across, moving tokens to the secret store

      For Claude Code, `mduct hook install claude` wires up the prompt index and
      the call redirect.
    EOS
  end

  test do
    assert_match "mduct", shell_output("#{bin}/mduct help")
    # a config it cannot load must fail loudly, naming the file — the daemon never starts here
    (testpath/"servers.jsonc").write('{"servers":{"broken":{}}}')
    output = shell_output("MDUCT_CONFIG=#{testpath}/servers.jsonc MDUCT_SOCKET=#{testpath}/s.sock #{bin}/mduct servers 2>&1", 1)
    assert_match "broken", output
  end
end
