# Generated by `bun run formula` in TheFox666/mduct — edit there, not here.
class Mduct < Formula
  desc "Every MCP server as a Unix tool: pipe it, script it, run it by hand"
  homepage "https://github.com/TheFox666/mduct"
  version "0.5.1"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/TheFox666/mduct/releases/download/v0.5.1/mduct-darwin-arm64"
      sha256 "c97745db6e78f3cca2fe1aeb3c36da773e64f93dbf52bb443d410ed51639a7f6"
    end
    on_intel do
      url "https://github.com/TheFox666/mduct/releases/download/v0.5.1/mduct-darwin-x64"
      sha256 "9906b92a646c91d2668a9fec9e9af8445381b5b025c98d620ca77d7159ccaa3a"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/TheFox666/mduct/releases/download/v0.5.1/mduct-linux-arm64"
      sha256 "f78e6537babae52a3270411cea32e5142bfe2e36361db2722aea31c0011902be"
    end
    on_intel do
      url "https://github.com/TheFox666/mduct/releases/download/v0.5.1/mduct-linux-x64"
      sha256 "03a85dfa44dd931b4d9e8ac9064ac413f0b2d8aadea61632394726dd0ec45afc"
    end
  end

  def install
    bin.install Dir["mduct-*"].first => "mduct"
  end

  def caveats
    <<~EOS
      Point mduct at your MCP servers in ~/.config/mduct/servers.jsonc, or import
      the ones you already have:

        mduct import            # lists servers found in your Claude configs
        mduct import gitlab     # copies one across, moving tokens to the secret store

      For Claude Code, `mduct hook install claude` wires up the prompt index and
      the call redirect.
    EOS
  end

  test do
    assert_match "mduct", shell_output("#{bin}/mduct help")
    # a config it cannot load must fail loudly, naming the file — the daemon never starts here
    (testpath/"servers.jsonc").write('{"servers":{"broken":{}}}')
    output = shell_output("MDUCT_CONFIG=#{testpath}/servers.jsonc MDUCT_SOCKET=#{testpath}/s.sock #{bin}/mduct servers 2>&1", 1)
    assert_match "broken", output
  end
end
