# Generated by `bun run formula` in TheFox666/mduct — edit there, not here.
class Mduct < Formula
  desc "Every MCP server as a Unix tool: pipe it, script it, run it by hand"
  homepage "https://github.com/TheFox666/mduct"
  version "0.7.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/TheFox666/mduct/releases/download/v0.7.0/mduct-darwin-arm64"
      sha256 "8834d87a021da140688b51b34aa68f1275546f5cc2938a68645bca1780b66265"
    end
    on_intel do
      url "https://github.com/TheFox666/mduct/releases/download/v0.7.0/mduct-darwin-x64"
      sha256 "0e2a89b40fff8003a21b2994b49c59dbc6e90d72ae701ea939da2b3c493c0e33"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/TheFox666/mduct/releases/download/v0.7.0/mduct-linux-arm64"
      sha256 "49a581fe1c7782b852c0583dea86741a2fbc126c0d482a2a7ef11dbe528c1642"
    end
    on_intel do
      url "https://github.com/TheFox666/mduct/releases/download/v0.7.0/mduct-linux-x64"
      sha256 "d216b1c414080521b3cc932f0982986ac4ad1f56536e628039b6f24bb53de4a8"
    end
  end

  def install
    bin.install Dir["mduct-*"].first => "mduct"
  end

  def caveats
    <<~EOS
      Point mduct at your MCP servers in ~/.config/mduct/servers.jsonc, or import
      the ones you already have:

        mduct import            # lists servers found in your Claude configs
        mduct import gitlab     # copies one across, moving tokens to the secret store

      For Claude Code, `mduct hook install claude` wires up the prompt index and
      the call redirect.
    EOS
  end

  test do
    assert_match "mduct", shell_output("#{bin}/mduct help")
    # a config it cannot load must fail loudly, naming the file — the daemon never starts here
    (testpath/"servers.jsonc").write('{"servers":{"broken":{}}}')
    output = shell_output("MDUCT_CONFIG=#{testpath}/servers.jsonc MDUCT_SOCKET=#{testpath}/s.sock #{bin}/mduct servers 2>&1", 1)
    assert_match "broken", output
  end
end
